name: MorningGlorySeeds
version: '${version}'
main: com.github.sigureruri.morninggloryseeds.MorningGlorySeeds
authors: [ SigureRuri ]
website: https://github.com/SigureRuri/MorningGlorySeeds
api-version: 1.15